kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "microservices-runtime.serviceAccountName" . }}-rolebinding
    namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "microservices-runtime.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "microservices-runtime.serviceAccountName" . }}-role
  apiGroup: ""