apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices-runtime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservices-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      appProtocol: http
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "microservices-runtime.selectorLabels" . | nindent 4 }}
