apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "microservices-runtime.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]