{{ if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "microservices-runtime.fullname" . }}
  name: microservices-runtime-storage
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: storage
    com.softwareag/release: {{ .Release.Name }}
  ports: 
  - protocol: TCP
    name: http
    port: {{ .Values.mysql.service.port  }}
    targetPort: {{ .Values.mysql.service.port  }}
{{- end -}}
