name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          path: main
          ref: main
      
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          path: repository
          ref: repository
      
      - name: Checkout generate-ui
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          path: generate-ui
          ref: generate-ui

      - name: Install binaries
        working-directory: main
        run: |
          for binary in "$(pwd)"/binary/*.deb; do
            echo "Installing $binary .. "
            sudo dpkg -i $binary
          done
          echo "All binaries are installed.."
          rm -rf binary

      - name: Cleanup repository branch
        working-directory: repository
        run: |
          rm -rf *

      - name: Create CNAME file
        working-directory: repository
        run: |
          echo "charts.webmethods.io" > CNAME

      - name: Package and index
        run: |
          echo "Begin repository handling and indexing..."
          
          # Package each chart and then index the repository
          cd repository
          REPOSITORY=$(pwd)
          cd ../generate-ui
          UI=$(pwd)
          cd ../main

          # run helm docs
          helm-docs

          WORKDIR=$(pwd)
          for subdir in "$WORKDIR"/*/; do
              if [[ -d "$subdir" && $(basename "$subdir") != "binary" ]]; then
                  echo "Processing directory: $subdir"
                  cd $UI
                  helmChartDocsPath=resources/static/helm-readmes/$(basename $subdir)
                  echo "Copy helm chart doc '$(basename $subdir)' to $helmChartDocsPath in UI branch.."
                  mkdir -p $helmChartDocsPath && cp $subdir/README.md $helmChartDocsPath
                  cd $REPOSITORY
                  helm package $subdir
                  cd $WORKDIR
              fi
          done
          cd $REPOSITORY
          helm repo index --url https://charts.webmethods.io/ .
          

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm packages
        working-directory: generate-ui
        run: |
          npm instal

      - name: Generate UI
        working-directory: generate-ui
        run: |
          cp ../repository/index.yaml .
          node generate-ui.js

      - name: Copy UI files to repository branch
        run: |
          uiBranch=$(pwd)/generate-ui
          cd $(pwd)/repository
          cp -r $uiBranch/node_modules .
          rm -rf node_modules/.bin
          mkdir -p resources/static/
          cp -r $uiBranch/resources/static/css resources/static/
          cp -r $uiBranch/resources/static/js resources/static/
          cp -r $uiBranch/resources/static/img resources/static/
          cp $uiBranch/index.html .
          mv node_modules wm_node_modules

      - name: Push to repository branch
        working-directory: repository
        run: |
          # Push changes to the repository branch
          git config --global user.email "SAGPrivateCloudBot@softwareag.com"
          git config --global user.name "SAG Private Cloud Bot"
          git add .
          git commit -m "Updating charts repository"
          git push
